server:
  port: 9019
  servlet:
    context-path: /ydms

spring:
  application:
    name: ydms-service

  messages:
    basename: i18n/messages
    cache-second: 3600
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ydms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true

ydms:
  jwt:
    secret: xxxxxx

info:
  app:
    version: "@project.version@"

logging:
  level:
    root: info
    cn:
      genlei: debug