server:
  port: 9019
  servlet:
    context-path: /

spring:
  application:
    name: ydms-service

  messages:
    basename: i18n/messages
    cache-second: 3600
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ydms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
  xxx-redis:
    host: 127.0.0.1
    port: 6379

ydms:
  jwt:
    secret: xxxxxx
  code:
    subject: YDMS重置密码验证码
    text: 您的验证码是 {code} , 10分钟内有效。

info:
  app:
    version: "@project.version@"

logging:
  level:
    root: info
    cn:
      genlei: debug